"""Telesign Verify API tool — Adaptive verification (SMS/Voice).

Exposes the Telesign Verify SMS API as an MCP tool. Supports both
sending OTPs and checking verification status.

Endpoints:
    POST /v1/verify/sms          — Send OTP
    GET  /v1/verify/{reference_id} — Check verification status
"""

from __future__ import annotations

from typing import Any

from pydantic import ValidationError

from telesign_mcp.client import TelesignClient
from telesign_mcp.exceptions import TelesignError
from telesign_mcp.logging import get_logger
from telesign_mcp.models.schemas import (
    VerifyInput,
    VerifyResponse,
    VerifyStatusInput,
)
from telesign_mcp.sanitize import mask_phone
from telesign_mcp.tools._helpers import format_error, format_success

logger = get_logger(__name__)

TOOL_NAME = "adaptive_verify"


async def adaptive_verify_send(
    client: TelesignClient,
    phone_number: str,
    verify_code: str | None = None,
    template: str | None = None,
    originating_ip: str | None = None,
) -> dict[str, Any]:
    """Send an OTP verification code via SMS to a phone number.

    Initiates a Telesign SMS verification by sending a one-time
    passcode to the specified phone number. The OTP can be
    auto-generated by Telesign or provided as a custom code.

    After calling this tool, use adaptive_verify_status with the
    returned reference_id to check whether the user entered the
    correct code.

    Args:
        client: Initialized TelesignClient instance.
        phone_number: Recipient phone in E.164 format (e.g., +15555550100).
        verify_code: Optional custom OTP (4–10 chars). If omitted,
            Telesign generates a secure code automatically.
        template: Optional SMS template. Use $$CODE$$ as the
            placeholder for the OTP code.
        originating_ip: Optional end-user IP for risk-aware routing.

    Returns:
        Structured dict containing reference_id for status polling,
        delivery status, and initial verify state.
    """
    # ── Validate inputs ─────────────────────────────────────────────
    try:
        validated = VerifyInput(
            phone_number=phone_number,
            verify_code=verify_code,
            template=template,
            originating_ip=originating_ip,
        )
    except ValidationError as exc:
        return format_error(TOOL_NAME, TelesignError(str(exc)))

    logger.info(
        "verify_send_request",
        phone=mask_phone(validated.phone_number),
        has_custom_code=validated.verify_code is not None,
    )

    # ── Build request ───────────────────────────────────────────────
    resource = "/v1/verify/sms"
    body_params: dict[str, str] = {
        "phone_number": validated.phone_number,
    }
    if validated.verify_code:
        body_params["verify_code"] = validated.verify_code
    if validated.template:
        body_params["template"] = validated.template
    if validated.originating_ip:
        body_params["originating_ip"] = validated.originating_ip

    # ── Execute API call ────────────────────────────────────────────
    try:
        raw_response = await client.post(resource, body_params=body_params)
    except TelesignError as exc:
        return format_error(TOOL_NAME, exc)

    # ── Parse response ──────────────────────────────────────────────
    try:
        parsed = VerifyResponse(**raw_response)
    except ValidationError:
        logger.warning(
            "verify_send_parse_warning",
            msg="Response did not match expected schema, returning raw",
        )
        return format_success(TOOL_NAME, raw_response)

    logger.info(
        "verify_send_complete",
        phone=mask_phone(validated.phone_number),
        reference_id=parsed.reference_id,
        status_code=parsed.status.code,
    )

    return format_success(TOOL_NAME, parsed.model_dump(exclude_none=True))


async def adaptive_verify_status(
    client: TelesignClient,
    reference_id: str,
    verify_code: str | None = None,
) -> dict[str, Any]:
    """Check the status of a verification transaction.

    Polls the Telesign Verify API to check whether an OTP was
    delivered and/or correctly entered by the end-user.

    If verify_code is provided, Telesign validates it against
    the original code and returns VALID/INVALID/EXPIRED state.

    Args:
        client: Initialized TelesignClient instance.
        reference_id: Transaction ID from the initial verify_send response.
        verify_code: Optional OTP entered by the user for validation.

    Returns:
        Structured dict with delivery status and code validation state.
    """
    # ── Validate inputs ─────────────────────────────────────────────
    try:
        validated = VerifyStatusInput(
            reference_id=reference_id,
            verify_code=verify_code,
        )
    except ValidationError as exc:
        return format_error(TOOL_NAME, TelesignError(str(exc)))

    logger.info(
        "verify_status_request",
        reference_id=validated.reference_id,
        has_code=validated.verify_code is not None,
    )

    # ── Build request ───────────────────────────────────────────────
    resource = f"/v1/verify/{validated.reference_id}"
    params: dict[str, str] = {}
    if validated.verify_code:
        params["verify_code"] = validated.verify_code

    # ── Execute API call ────────────────────────────────────────────
    try:
        raw_response = await client.get(resource, params=params)
    except TelesignError as exc:
        return format_error(TOOL_NAME, exc)

    # ── Parse response ──────────────────────────────────────────────
    try:
        parsed = VerifyResponse(**raw_response)
    except ValidationError:
        logger.warning(
            "verify_status_parse_warning",
            msg="Response did not match expected schema, returning raw",
        )
        return format_success(TOOL_NAME, raw_response)

    logger.info(
        "verify_status_complete",
        reference_id=validated.reference_id,
        code_state=parsed.verify.code_state if parsed.verify else None,
    )

    return format_success(TOOL_NAME, parsed.model_dump(exclude_none=True))
